---
name: hadoop

releases:
- name: hadoop
  version: latest

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 2
  max_in_flight: 1
  canary_watch_time: 5000-60000
  update_watch_time: 5000-60000

instance_groups:

- name: namenode
  azs: [z1]
  instances: 1
  jobs:
  - name: namenode
    release: pravega
    properties: {}
  vm_type: default
  stemcell: default
  persistent_disk: 10240
  networks:
  - name: default

- name: datanodes
  azs: [z1, z2, z3]
  instances: 3
  jobs:
  - name: datanode
    release: pravega
    properties: {}
  vm_type: default
  stemcell: default
  persistent_disk: 10240
  networks:
  - name: default
